# Generated by Django 3.0.3 on 2020-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projektit',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projektit',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
