# Generated by Django 3.0.3 on 2020-02-06 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0002_auto_20200206_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektit',
            name='shortdescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
