# Generated by Django 3.0.3 on 2020-02-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0003_projektit_shortdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projektit',
            new_name='Projekti',
        ),
    ]
