# Generated by Django 3.0.3 on 2020-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0004_auto_20200207_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekti',
            name='app_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
